name: Release

on:
  pull_request:
    types: [closed]
    tags:
      - 'v*'

jobs:
  release:
    if: github.event.pull_request.merged == true)
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            See [CHANGELOG.md](https://github.com/elastisys/ck8s-cluster/blob/v${{ steps.get_version.outputs.VERSION }}/CHANGELOG.md) for details.
